Shifted to bash for these, so _dbsettings can have function to compute database names.

diff --git a/db_transition b/db_transition
--- a/db_transition
+++ b/db_transition
@@ -1,37 +1,60 @@
-#!/bin/tcsh
+#!/bin/bash
 
 
-echo ""
-echo "Usage: $0 [-f]"
-echo "---------------------------------------------------------------------"
-echo "  Creates a new database version from the old one. Assumes DBVER -1."
-echo "  Or, if ver1, just creates it."
-echo ""
-echo " -f - force 'yes' response to continue"
-echo ""
+retval=0
+isforced=0
+
+ErrorOut() {
+    retval=1
+    echo "ERROR: .... stuff"
+    echo "   $*"
+    DisplayOptions $0
+}
+
+DisplayOptions() {
+    echo ""
+    echo "Usage: "`basename $0`" [-f]"
+    echo "---------------------------------------------------------------------"
+    echo "  Creates a new database version from the old one. Assumes DBVER -1."
+    echo "  Or, if ver1, just creates it."
+    echo ""
+    echo "    -f/--force - force 'yes' response to continue"
+    echo "     -h/--help - this help message"
+    echo ""
+    exit $retval
+}
 
 
-# Check for 'forced' setting
-set isforced=0
-if ( $# == 1 ) then
-	if ( "$1" == "-f" ) then
-	   	set isforced=1
-	endif
-endif
+
 
 # Load settings
-set cwd=`pwd`"/."
-set p=`dirname $cwd`
-source $p/_dbsettings.tcsh
-if ( $? != 0 ) then
+cwd=`pwd`"/."
+p=`dirname $cwd`
+source $p/_dbsettings
+if [ $? != 0 ]; then
 	echo "ERROR: no _dbsettings.tcsh file. Are you calling from the wrong directory?"
 	exit 1
-endif
+fi
+
+
+while [ "`echo $1 | cut -c 1`" == "-" ]; do
+    if [ "$1" == "-h" -o "$1" == "--help" ]; then
+        DisplayOptions $*
+    elif [ "$1" == "-f" -o "$1" == "--force" ]; then
+        isforced=1
+    else
+        echo "ERROR: unknown argument '$1'"
+        ErrorOut
+    fi
+    shift
+done
+
 
 # Defines
-set LS="$p/.rebuild.sql"
-set OLDDBVER = `php -r "echo $DBVER-1;";`
-set OLDDBNAME=$APPNAME"_"$ENVIRONMENT"_"$OLDDBVER
+LS="$p/.rebuild.sql"
+OLDDBVER=`php -r "echo $DBVER-1;";`
+OLDDBNAME=$(ComputeDBName $APPNAME $ENVIRONMENT $OLDDBVER)
+echo "OLDDBNAME $OLDDBNAME $APPNAME $ENVIRONMENT $OLDDBVER"
 
 echo ""
 echo " Settings..."
@@ -39,45 +62,46 @@ echo "---------------------------------------------------------------------"
 #echo "   state : $INSTRAPPTION"
 echo "     DBVER : $DBVER"
 echo "    DBNAME : $DBNAME"
-if ( "$DBVER" != "1" ) then
+if [ "$DBVER" != "1" ]; then
 	echo "  OLDDBVER : $OLDDBVER"
 	echo " OLDDBNAME : $OLDDBNAME"
-endif
+fi
 
 
 echo ""
 echo ""
 echo "Run pretests"
 echo "---------------------------------------------------------------------"
-if ( -f $p/ver$DBVER/pretest.tcsh ) then
+if [ -f $p/ver$DBVER/pretest.tcsh ]; then
 	source $p/ver$DBVER/pretest.tcsh
-	if ( $? == 0 ) then 
+	if [ $? == 0 ]; then 
    		echo "   ... passed"
-	else exit 1
-	endif
+	else 
+      exit 1
+	fi
 else 
 	echo "  ... no pretest"
-endif
+fi
 
 
 # for first version, just reload it, nothing to transition
-if ( $DBVER == 1 ) then
+if [ $DBVER == 1 ]; then
 	echo ""
 	echo ""
 	echo "CONFIRM: Continuing will rebuild database."
 	echo "---------------------------------------------------------------------"
 	echo -n "REBUILD DATABASE [y/N] > "
-	if ( "$isforced" == "1" ) then 
-		set isready="Y"
+	if [ "$isforced" == "1" ]; then 
+		isready="Y"
 	else
-		set isready=$<
-	endif
-	if ( ! ($isready == "Y" || $isready == "y") ) then
+    read isready
+	fi
+	if [ ! \($isready == "Y" -o $isready == "y"\) ]; then
 		echo ""
 		echo "... EXITING"
 		echo ""
 		exit 1
-	endif
+	fi
 else 
 	echo ""
 	echo ""
@@ -87,35 +111,35 @@ else
 	echo "             $OLDDBNAME --> $DBNAME "
 	echo "---------------------------------------------------------------------"
 	echo -n "DELETE AND BUILD DATABASE [y/N] > "
-	if ( $isforced == 1 ) then 
-		set isready= 'Y'
+	if [ $isforced == 1 ]; then 
+		isready= 'Y'
 	else
-		set isready=$<
-	endif
-	if ( ! ($isready == "Y" || $isready == "y") ) then
+    read isready
+	fi
+	if ! [ "$isready" == "Y" -o "$isready" == "y" ] ; then
 		echo ""
 		echo "... EXITING"
 		echo ""
 		exit 1
-	endif
+	fi
 
 
 	echo ""
 	echo ""
 	echo "Save $OLDDBNAME to file."
 	echo "---------------------------------------------------------------------"
-	$p/db_saveall -s $ENVIRONMENT $OLDDBVER
-	if ( $? != 0 ) then
+	db_saveall -s $ENVIRONMENT $OLDDBVER
+	if [ $? != 0 ]; then
 		echo " : failed. exiting now."
 		echo ""
 		exit 1
-	endif
-	set latestdump = `ls -tra $p/dumps/dump_20[0-9][0-9]_*.sql | tail -n 1`
+	fi
+	latestdump=`ls -tra $p/dumps/dump_20[0-9][0-9]_*.sql | tail -n 1`
 	echo "    : success, file: $latestdump"
 	echo ""
 
 
-endif
+fi
 
 echo ""
 echo ""
@@ -127,15 +151,14 @@ echo "create database $DBNAME;" >> $LS
 #echo "grant all privileges on $DBNAME.* to $APPNAME@localhost;" >> $LS 
 #mysql -u root -p < $LS
 mysql --defaults-file=$p/.my.cnf < $LS
-if ( $? != 0 ) then
+if [ $? != 0 ]; then
 	echo ""
 	echo "FAILED building database... wrong password?";
-	echo ""
-	echo "  Or, 1st time run, user needs access to create/drop. Run this as root"
-	echo " grant all privileges on `$APPNAME_%`.* to `$APPNAME`@`localhost`;"
+	echo " ...Or, 1st time run, user needs access to create/drop. Run this as root:"
+	echo "   'grant all privileges on \`"$DBNAME"\`.* to \`$DBUSER\`@\`localhost\`;"
 	echo ""
 	exit 1
-endif
+fi
 
 
 
@@ -145,25 +168,25 @@ echo "Build import script ($LS)"
 echo "---------------------------------------------------------------------"
 echo "" > $LS
 echo "use $DBNAME;" >> $LS
-if ( "$DBVER" != "1" ) then
+if [ "$DBVER" != "1" ]; then
    	echo "source $latestdump;" >> $LS
-endif
-if ( ! -f $p/ver$DBVER/load.sql ) then
+fi
+if [ ! -f $p/ver$DBVER/load.sql ]; then
 	echo "ERROR: No $p/ver$DBVER/load.sql file"
 	exit 1
-endif
+fi
 echo "source $p/ver$DBVER/load.sql;" >> $LS
-if ( -f $p/ver$DBVER/load_$ENVIRONMENT.sql ) then
+if [ -f $p/ver$DBVER/load_$ENVIRONMENT.sql ]; then
     echo " ...found load file for $ENVIRONMENT."
     echo "source $p/ver$DBVER/load_$ENVIRONMENT.sql;" >> $LS
-endif
+fi
 echo " ...done"
 
 echo ""
 echo "Run import script"
 echo "---------------------------------------------------------------------"
 mysql --defaults-file=$p/.my.cnf < $LS
-if ( $? == 0 ) then
+if [ $? == 0 ]; then
 	echo " ...SUCCESS!"
 	echo 
 	echo " ... successfully created database $DBNAME"
@@ -171,4 +194,8 @@ if ( $? == 0 ) then
 else
 	echo "ERROR: failed importing the script"
 	exit 1
-endif
+fi
+
+exit $retval
+
+
