Wasn't counting arguments corretly and erroing out.

diff --git a/v2/db_savetable b/v2/db_savetable
--- a/v2/db_savetable
+++ b/v2/db_savetable
@@ -2,10 +2,11 @@
 
 
 ErrorOut() {
-    retval=1
-    echo "ERROR: .... stuff"
-    echo "   $*"
+    echo 
+    echo "ERROR: $*"
+    echo 
     DisplayOptions $0
+    exit 1
 }
 
 DisplayOptions() {
@@ -51,8 +52,7 @@ while [ "`echo $1 | cut -c 1`" == "-" ]; do
 done
 
 if [ $# -le 2 ]; then
-    echo "ERROR: Bad arguments"
-    ErrorOut
+    ErrorOut "Bad arguments"
 fi
 
 
